/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Blender3D (https://sketchfab.com/Blender3D)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/0d62f4d3676545c88ec8523213c055dd
title: Minecraft Diamond Axe
*/
 
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
        
import React, { useRef } from 'react'
import { useGLTF, 

 } from '@react-three/drei'


export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/right-hand-white-webxr-tracking-ready/model.gltf')
  return (
    <group ref={group} {...props} dispose={null} rotation={[Math.PI / 2, Math.PI, -Math.PI]}>
<primitive object={nodes.wrist} />
<primitive object={nodes['thumb-metacarpal']} />
<primitive object={nodes['thumb-phalanx-proximal']} />
<primitive object={nodes['thumb-phalanx-distal']} />
<primitive object={nodes['thumb-tip']} />
<primitive object={nodes['index-finger-metacarpal']} />
<primitive object={nodes['index-finger-phalanx-proximal']} />
<primitive object={nodes['index-finger-phalanx-intermediate']} />
<primitive object={nodes['index-finger-phalanx-distal']} />
<primitive object={nodes['index-finger-tip']} />
<primitive object={nodes['middle-finger-metacarpal']} />
<primitive object={nodes['middle-finger-phalanx-proximal']} />
<primitive object={nodes['middle-finger-phalanx-intermediate']} />
<primitive object={nodes['middle-finger-phalanx-distal']} />
<primitive object={nodes['middle-finger-tip']} />
<primitive object={nodes['ring-finger-metacarpal']} />
<primitive object={nodes['ring-finger-phalanx-proximal']} />
<primitive object={nodes['ring-finger-phalanx-intermediate']} />
<primitive object={nodes['ring-finger-phalanx-distal']} />
<primitive object={nodes['ring-finger-tip']} />
<primitive object={nodes['pinky-finger-metacarpal']} />
<primitive object={nodes['pinky-finger-phalanx-proximal']} />
<primitive object={nodes['pinky-finger-phalanx-intermediate']} />
<primitive object={nodes['pinky-finger-phalanx-distal']} />
<primitive object={nodes['pinky-finger-tip']} />
<skinnedMesh geometry={nodes.r_handMeshNode.geometry} material={materials.lambert2} skeleton={nodes.r_handMeshNode.skeleton} />

    </group>
  )
}

useGLTF.preload('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/right-hand-white-webxr-tracking-ready/model.gltf')